import { useEffect, useMemo, useState } from 'react';
import Layout from '../components/Layout.jsx';
import Icon from '../components/Icon.jsx';
import Spinner from '../components/Spinner.jsx';
import { Alert, EmptyState, MetricCard, PageHeader } from '../components/UI.jsx';
import { api } from '../lib/api.js';
import { useAuth } from '../App.jsx';

function FeatureNotice({ children }) { return <div style={{ marginBottom: 18 }}><Alert tone="warning">{children}</Alert></div>; }
function FeaturePage({ eyebrow, title, description, children, actions }) { return <Layout><div className="page"><PageHeader eyebrow={eyebrow} title={title} description={description} actions={actions} />{children}</div></Layout>; }
function Toolbar({ children }) { return <div className="feature-toolbar">{children}</div>; }
function DetailRow({ label, value, muted = false }) { return <div className="detail-row"><span>{label}</span><strong className={muted ? 'muted' : ''}>{value}</strong></div>; }

export function Analytics() {
  const [projects, setProjects] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('All');
  useEffect(() => { api.get('/projects').then(setProjects).catch(() => {}).finally(() => setLoading(false)); }, []);
  const visibleProjects = filter === 'All' ? projects : projects.filter(project => project.status === filter.toLowerCase());
  const approved = visibleProjects.filter(project => project.status === 'approved').length;
  const waiting = visibleProjects.filter(project => project.status === 'waiting').length;
  const files = visibleProjects.reduce((total, project) => total + (project.files?.length || 0), 0);
  const approvalRate = visibleProjects.length ? Math.round((approved / visibleProjects.length) * 100) + '%' : '—';
  function exportAnalytics() {
    const rows = [['Project', 'Status', 'Files'], ...visibleProjects.map(project => [project.name, project.status, project.files?.length || 0])];
    const csv = rows.map(row => row.map(value => '"' + String(value).replaceAll('"', '""') + '"').join(',')).join('\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }));
    const link = document.createElement('a'); link.href = url; link.download = 'loop-analytics.csv'; link.click(); URL.revokeObjectURL(url);
  }
  return <FeaturePage eyebrow="Workspace intelligence" title="Analytics" description="Understand your review pipeline with data from the projects already in Loop.">
    <FeatureNotice>Deployment, traffic, build-time, and error analytics will appear when deployment event tracking is connected. Current cards use your live project data.</FeatureNotice>
    {loading ? <div className="empty-state"><Spinner size={30} color="var(--violet-bright)" /></div> : projects.length === 0 ? <div className="panel"><EmptyState icon="chart" title="Analytics start with your first project" description="Create a project and collect feedback to begin seeing meaningful workspace trends." /></div> : <>
      <Toolbar><div className="filter-tabs">{['All', 'Ready', 'Waiting', 'Approved'].map(item => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div><button className="btn btn-secondary btn-sm" type="button" onClick={exportAnalytics} disabled={!visibleProjects.length}><Icon name="upload" size={14} />Export CSV</button></Toolbar>
      {visibleProjects.length === 0 ? <div className="panel"><EmptyState icon="search" title="No projects in this status" description="Choose another status filter to see the live project records." /></div> : <><div className="metric-grid"><MetricCard icon="folder" label="Projects tracked" value={visibleProjects.length} detail="Live project records" /><MetricCard icon="upload" label="Files reviewed" value={files} detail="Across filtered projects" tone="cyan" /><MetricCard icon="circleCheck" label="Approval rate" value={approvalRate} detail={approved + ' approved'} tone="green" /><MetricCard icon="clock" label="Awaiting feedback" value={waiting} detail={waiting ? 'Needs attention' : 'All clear'} tone="amber" /></div>
      <div className="feature-grid"><section className="panel"><div className="panel__header"><div><div className="panel__title">Review status</div><div className="panel__subtitle">A live breakdown of your current project pipeline.</div></div></div><div className="panel__body"><div className="bar-chart">{visibleProjects.map(project => <div className="bar-chart__item" key={project.id}><span className={'bar-chart__bar bar-chart__bar--' + project.status} style={{ height: project.status === 'approved' ? '86%' : project.status === 'ready' ? '62%' : '38%' }} /><small title={project.name}>{project.name}</small></div>)}</div><div className="chart-legend"><span><i className="legend-dot legend-dot--approved" />Approved</span><span><i className="legend-dot legend-dot--ready" />Ready</span><span><i className="legend-dot legend-dot--waiting" />Waiting</span></div></div></section><section className="panel"><div className="panel__header"><div><div className="panel__title">Data coverage</div><div className="panel__subtitle">What Loop can measure today.</div></div></div><div className="panel__body"><DetailRow label="Project activity" value="Connected" /><DetailRow label="Feedback volume" value="Connected" /><DetailRow label="Deployment frequency" value="Not connected" muted /><DetailRow label="Traffic & bandwidth" value="Not connected" muted /><DetailRow label="Build performance" value="Not connected" muted /></div></section></div></>}
    </>}</FeaturePage>;
}

export function Deployments() {
  return <FeaturePage eyebrow="Delivery pipeline" title="Deployments" description="Track releases, environments, build stages, and rollback history from one timeline."><FeatureNotice>Loop does not currently have a deployment provider or deployment-events API connected. This surface is ready for that integration without fabricating release data.</FeatureNotice><div className="panel"><div className="panel__header"><div><div className="panel__title">Deployment timeline</div><div className="panel__subtitle">Production, preview, and development releases will appear here.</div></div><button className="btn btn-secondary btn-sm" disabled><Icon name="external" size={14} />Connect provider</button></div><EmptyState icon="zap" title="No deployment events yet" description="Connect a deployment source when that backend integration is available to see build progress, URLs, durations, and rollback actions." /></div></FeaturePage>;
}

export function Logs() {
  return <FeaturePage eyebrow="Runtime visibility" title="Logs" description="Searchable build and runtime output for every environment."><FeatureNotice>Live log streaming requires deployment and runtime log endpoints that are not present in the current server.</FeatureNotice><div className="panel log-console"><div className="panel__header"><div><div className="panel__title">Live output</div><div className="panel__subtitle">Waiting for a connected deployment source.</div></div><div className="log-console__actions"><button className="btn btn-ghost btn-sm" disabled><Icon name="search" size={14} />Search</button><button className="btn btn-ghost btn-sm" disabled>Export</button></div></div><div className="log-console__body"><span className="log-console__prompt">$ loop logs --follow</span><span className="log-console__cursor" /><p>No log stream connected.</p><small>Build and runtime entries will be shown here once a provider is configured.</small></div></div></FeaturePage>;
}

export function Domains() {
  const [domains, setDomains] = useState([]);
  const [domain, setDomain] = useState('');
  const [message, setMessage] = useState('');
  function addDomain(event) { event.preventDefault(); const value = domain.trim().toLowerCase(); if (!value) return; setDomains(current => [...current, { id: Date.now(), name: value }]); setDomain(''); setMessage('Domain added to this local preview. Verification needs a connected domain API.'); }
  return <FeaturePage eyebrow="Project delivery" title="Domains" description="Connect custom domains, verify DNS, and manage SSL for your review links."><FeatureNotice>{message || 'Domain changes are shown locally in this UI preview and are not persisted because the current backend has no domains table or endpoint.'}</FeatureNotice><div className="feature-grid"><section className="panel"><div className="panel__header"><div><div className="panel__title">Add a domain</div><div className="panel__subtitle">Use a custom hostname for client-facing reviews.</div></div></div><div className="panel__body"><form className="inline-form" onSubmit={addDomain}><input className="form-input" required value={domain} onChange={event => setDomain(event.target.value)} placeholder="reviews.example.com" aria-label="Domain name" /><button className="btn btn-primary" type="submit"><Icon name="plus" size={14} />Add domain</button></form><div className="setup-steps"><div className="setup-step setup-step--active"><span>01</span><div><strong>Verify DNS</strong><small>Add the provided DNS record at your registrar.</small></div></div><div className="setup-step"><span>02</span><div><strong>Issue SSL</strong><small>Secure your review links automatically.</small></div></div><div className="setup-step"><span>03</span><div><strong>Set primary</strong><small>Choose the default domain for sharing.</small></div></div></div></div></section><section className="panel"><div className="panel__header"><div><div className="panel__title">Connected domains</div><div className="panel__subtitle">Your verified review destinations.</div></div></div>{domains.length === 0 ? <EmptyState icon="link" title="No custom domains" description="Your Loop review links continue to work on the default domain." /> : <div className="panel__body">{domains.map(item => <div className="resource-row" key={item.id}><span className="resource-row__icon"><Icon name="link" size={15} /></span><div><strong>{item.name}</strong><small>Added just now · SSL pending</small></div><span className="badge badge-waiting">Verification pending</span></div>)}</div>}</section></div></FeaturePage>;
}

export function EnvironmentVariables() {
  const [variables, setVariables] = useState([]);
  const [form, setForm] = useState({ key: '', value: '', scope: 'Preview' });
  const [message, setMessage] = useState('');
  function addVariable(event) { event.preventDefault(); if (!form.key.trim() || !form.value) return; setVariables(current => [...current, { id: Date.now(), key: form.key.trim().toUpperCase(), scope: form.scope }]); setForm({ key: '', value: '', scope: 'Preview' }); setMessage('Variable added to this local preview. Its value was cleared and is never displayed.'); }
  function removeVariable(id) { if (window.confirm('Remove this environment variable from the local preview?')) setVariables(current => current.filter(item => item.id !== id)); }
  return <FeaturePage eyebrow="Secure configuration" title="Environment variables" description="Manage configuration by environment without exposing secret values."><FeatureNotice>{message || 'Values are intentionally masked and held only in this page preview. Persistence requires a secure backend environment-variable service.'}</FeatureNotice><div className="feature-grid"><section className="panel"><div className="panel__header"><div><div className="panel__title">Add variable</div><div className="panel__subtitle">Choose the environment where it should apply.</div></div><Icon name="lock" size={17} /></div><div className="panel__body"><form className="auth-form" onSubmit={addVariable}><div className="form-group"><label className="form-label" htmlFor="variable-key">Key</label><input id="variable-key" className="form-input mono" required value={form.key} onChange={event => setForm(current => ({ ...current, key: event.target.value }))} placeholder="PUBLIC_APP_URL" /></div><div className="form-group"><label className="form-label" htmlFor="variable-value">Value</label><input id="variable-value" className="form-input" type="password" required value={form.value} onChange={event => setForm(current => ({ ...current, value: event.target.value }))} placeholder="Value stays hidden" /></div><div className="form-group"><label className="form-label" htmlFor="variable-scope">Environment</label><select id="variable-scope" className="form-input" value={form.scope} onChange={event => setForm(current => ({ ...current, scope: event.target.value }))}><option>Production</option><option>Preview</option><option>Development</option></select></div><button className="btn btn-primary" type="submit"><Icon name="lock" size={14} />Add securely</button></form></div></section><section className="panel"><div className="panel__header"><div><div className="panel__title">Variables</div><div className="panel__subtitle">Search and reveal controls will be wired to secure storage later.</div></div></div>{variables.length === 0 ? <EmptyState icon="lock" title="No variables added" description="Add a variable to preview the protected configuration workflow." /> : <div className="panel__body">{variables.map(item => <div className="resource-row" key={item.id}><span className="resource-row__icon"><Icon name="lock" size={15} /></span><div><strong className="mono">{item.key}</strong><small>{item.scope} · ••••••••••••</small></div><button className="icon-button" type="button" onClick={() => removeVariable(item.id)} aria-label={'Remove ' + item.key}><Icon name="close" size={15} /></button></div>)}</div>}</section></div></FeaturePage>;
}

const INTEGRATIONS = [
  { id: 'github', name: 'GitHub', type: 'Source control', icon: 'code', description: 'Import repositories and keep project context close to review.' },
  { id: 'gitlab', name: 'GitLab', type: 'Source control', icon: 'code', description: 'Keep merge requests and review context connected.' },
  { id: 'bitbucket', name: 'Bitbucket', type: 'Source control', icon: 'code', description: 'Bring repository activity into your project workflow.' },
  { id: 'supabase', name: 'Supabase', type: 'Data & auth', icon: 'layers', description: 'Connect project data, storage, and authentication.' },
  { id: 'stripe', name: 'Stripe', type: 'Billing', icon: 'sparkle', description: 'Manage subscription checkout and customer billing.' },
  { id: 'slack', name: 'Slack', type: 'Notifications', icon: 'bell', description: 'Send review and approval events to a team channel.' },
  { id: 'discord', name: 'Discord', type: 'Notifications', icon: 'users', description: 'Share team updates with a connected community channel.' },
  { id: 'email', name: 'Email', type: 'Notifications', icon: 'user', description: 'Route important review events to your inbox.' },
  { id: 'monitoring', name: 'Monitoring', type: 'Observability', icon: 'activity', description: 'Connect alerting for uptime and service health.' },
];
export function Integrations() {
  const [connected, setConnected] = useState(['supabase', 'stripe']);
  return <FeaturePage eyebrow="Connected tools" title="Integrations" description="Bring your source control, data, billing, and team communication into Loop."><FeatureNotice>Connection changes are a UI preview only. Existing Supabase and Stripe functionality remains available through the current app; new provider actions require backend endpoints and OAuth configuration.</FeatureNotice><div className="integration-grid">{INTEGRATIONS.map(item => <section className="panel integration-card" key={item.id}><div className="integration-card__top"><span className="integration-card__icon"><Icon name={item.icon} size={20} /></span><span className={'connection-dot ' + (connected.includes(item.id) ? 'is-connected' : '')} title={connected.includes(item.id) ? 'Connected' : 'Not connected'} /></div><span className="eyebrow">{item.type}</span><h2>{item.name}</h2><p>{item.description}</p><button className={'btn ' + (connected.includes(item.id) ? 'btn-secondary' : 'btn-primary') + ' btn-full'} onClick={() => setConnected(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])}>{connected.includes(item.id) ? 'Connected · Configure' : 'Connect integration'}</button></section>)}</div></FeaturePage>;
}

export function Team() {
  const { profile, session } = useAuth();
  const [members, setMembers] = useState([{ id: 'owner', name: profile?.name || session?.user?.email?.split('@')[0] || 'You', email: profile?.email || session?.user?.email || '', role: 'Owner', status: 'Active' }]);
  const [form, setForm] = useState({ email: '', role: 'Developer' }); const [message, setMessage] = useState('');
  function invite(event) { event.preventDefault(); if (!form.email.trim()) return; setMembers(current => [...current, { id: Date.now(), name: form.email.split('@')[0], email: form.email.trim(), role: form.role, status: 'Invite pending' }]); setForm({ email: '', role: 'Developer' }); setMessage('Invite staged locally. Sending requires a team-members backend endpoint.'); }
  return <FeaturePage eyebrow="Collaboration" title="Team" description="Invite collaborators and keep permissions clear across the workspace."><FeatureNotice>{message || 'Members shown here are local UI state until the team and invitation APIs are available.'}</FeatureNotice><div className="feature-grid"><section className="panel"><div className="panel__header"><div><div className="panel__title">Invite a teammate</div><div className="panel__subtitle">Choose the least privilege role they need.</div></div></div><div className="panel__body"><form className="inline-form" onSubmit={invite}><input className="form-input" type="email" required value={form.email} onChange={event => setForm(current => ({ ...current, email: event.target.value }))} placeholder="teammate@studio.com" aria-label="Teammate email" /><select className="form-input" value={form.role} onChange={event => setForm(current => ({ ...current, role: event.target.value }))} aria-label="Team role"><option>Admin</option><option>Developer</option><option>Viewer</option></select><button className="btn btn-primary" type="submit"><Icon name="plus" size={14} />Invite</button></form><div className="role-list"><DetailRow label="Owner" value="Full workspace access" /><DetailRow label="Admin" value="Manage members and settings" /><DetailRow label="Developer" value="Create and manage projects" /><DetailRow label="Viewer" value="Read-only access" /></div></div></section><section className="panel"><div className="panel__header"><div><div className="panel__title">Members · {members.length}</div><div className="panel__subtitle">Active collaborators and pending invites.</div></div></div><div className="panel__body">{members.map(member => <div className="resource-row" key={member.id}><span className="profile-avatar">{member.name.substring(0, 2).toUpperCase()}</span><div><strong>{member.name}</strong><small>{member.email}</small></div><span className="member-role">{member.role}</span><span className="muted" style={{ fontSize: 10 }}>{member.status}</span></div>)}</div></section></div></FeaturePage>;
}

const NOTIFICATION_ITEMS = [{ id: 1, category: 'System', title: 'Welcome to Loop', text: 'Your workspace is ready for its first review.', unread: true }, { id: 2, category: 'Security', title: 'Authentication is active', text: 'Supabase is protecting your account session.', unread: false }];
export function Notifications() {
  const [items, setItems] = useState(NOTIFICATION_ITEMS); const [prefs, setPrefs] = useState({ deployment: true, security: true, billing: true, team: false });
  return <FeaturePage eyebrow="Stay in the loop" title="Notifications" description="Keep important workspace events visible without adding more noise."><div className="feature-grid"><section className="panel"><div className="panel__header"><div><div className="panel__title">Inbox</div><div className="panel__subtitle">Deployment, security, billing, and team updates.</div></div><button className="btn btn-ghost btn-sm" onClick={() => setItems(current => current.map(item => ({ ...item, unread: false })))}>Mark all read</button></div><div className="notification-list">{items.map(item => <button className={'notification-row ' + (item.unread ? 'is-unread' : '')} key={item.id} onClick={() => setItems(current => current.map(entry => entry.id === item.id ? { ...entry, unread: false } : entry))}><span className="quick-action__icon"><Icon name={item.category === 'Security' ? 'shield' : 'bell'} size={15} /></span><span><strong>{item.title}</strong><small>{item.category} · {item.text}</small></span>{item.unread && <i className="unread-dot" />}</button>)}</div></section><section className="panel"><div className="panel__header"><div><div className="panel__title">Preferences</div><div className="panel__subtitle">Choose what reaches your workspace inbox.</div></div></div><div className="panel__body">{Object.entries(prefs).map(([key, value]) => <label className="toggle-row" key={key}><span><strong>{key[0].toUpperCase() + key.slice(1)} events</strong><small>Receive relevant {key} updates.</small></span><input type="checkbox" checked={value} onChange={() => setPrefs(current => ({ ...current, [key]: !current[key] }))} /></label>)}</div></section></div></FeaturePage>;
}

export function Activity() {
  const [projects, setProjects] = useState([]); const [filter, setFilter] = useState('All');
  useEffect(() => { api.get('/projects').then(setProjects).catch(() => {}); }, []);
  const events = useMemo(() => projects.map(project => ({ id: project.id, title: 'Project created: ' + project.name, text: (project.client_name || 'No client') + ' · ' + new Date(project.created_at).toLocaleDateString(), category: 'Projects' })), [projects]); const visible = filter === 'All' ? events : events.filter(event => event.category === filter);
  return <FeaturePage eyebrow="Workspace history" title="Activity" description="A chronological record of the changes that matter to your review workflow."><Toolbar><div className="filter-tabs">{['All', 'Projects', 'Security', 'Billing'].map(item => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div><span className="muted" style={{ fontSize: 11 }}>{visible.length} events</span></Toolbar><section className="panel">{visible.length === 0 ? <EmptyState icon="activity" title="No activity in this view" description={projects.length ? 'Try a different filter.' : 'Workspace events will appear after you create a project.'} /> : <div className="activity-list">{visible.map(event => <div className="activity-row" key={event.id}><span className="activity-row__line" /><span className="quick-action__icon"><Icon name="folder" size={15} /></span><div><strong>{event.title}</strong><small>{event.text}</small></div></div>)}</div>}</section></FeaturePage>;
}

export function Security() {
  const { session } = useAuth(); const email = session?.user?.email || 'Authenticated account';
  return <FeaturePage eyebrow="Trust center" title="Security" description="Review account protection, sessions, login history, and developer access."><FeatureNotice>Session and authentication status below come from the active Supabase session. Login history, device management, API keys, and 2FA require additional backend/provider configuration.</FeatureNotice><div className="feature-grid"><section className="panel"><div className="panel__header"><div><div className="panel__title">Authentication status</div><div className="panel__subtitle">Current account protection.</div></div><span className="badge badge-approved">Protected</span></div><div className="panel__body"><DetailRow label="Account" value={email} /><DetailRow label="Provider" value="Supabase Auth" /><DetailRow label="Session" value="Active" /><DetailRow label="Two-factor authentication" value="Not configured" muted /></div></section><section className="panel"><div className="panel__header"><div><div className="panel__title">Access controls</div><div className="panel__subtitle">Additional security layers.</div></div></div><div className="panel__body"><div className="security-action"><span className="quick-action__icon"><Icon name="shield" size={15} /></span><div><strong>Active sessions</strong><small>Session management requires a provider endpoint.</small></div><button className="btn btn-secondary btn-sm" disabled>Review</button></div><div className="security-action"><span className="quick-action__icon"><Icon name="lock" size={15} /></span><div><strong>Recovery methods</strong><small>Password recovery is available from the sign-in screen.</small></div><button className="btn btn-secondary btn-sm" disabled>Manage</button></div></div></section></div></FeaturePage>;
}

export function Developer() {
  const apiBase = import.meta.env.VITE_API_BASE_URL?.trim() || '/api';
  return <FeaturePage eyebrow="Build with Loop" title="Developer tools" description="Manage programmatic access, webhooks, and event delivery for your workspace."><FeatureNotice>The current backend does not expose API-key, webhook, or event-history endpoints. The visible values below are non-secret configuration metadata only.</FeatureNotice><div className="feature-grid"><section className="panel"><div className="panel__header"><div><div className="panel__title">API keys</div><div className="panel__subtitle">Keys will be shown once at creation and never stored in the UI.</div></div><button className="btn btn-primary btn-sm" disabled><Icon name="plus" size={14} />Create key</button></div><EmptyState icon="lock" title="No API keys" description="Connect the developer API before creating programmatic access." /></section><section className="panel"><div className="panel__header"><div><div className="panel__title">API connection</div><div className="panel__subtitle">The client’s configured request base.</div></div></div><div className="panel__body"><DetailRow label="Base path" value={apiBase} /><DetailRow label="Authentication" value="Bearer Supabase session" /><DetailRow label="Webhooks" value="Not connected" muted /></div></section></div></FeaturePage>;
}

const BILLING_PLANS = [{ id: 'solo', name: 'Solo', price: '$9', features: '5 active projects' }, { id: 'studio', name: 'Studio', price: '$29', features: 'Unlimited projects' }];
export function Billing() {
  const { profile } = useAuth(); const [loading, setLoading] = useState(''); const [error, setError] = useState('');
  async function checkout(plan) { setLoading(plan); setError(''); try { const { url } = await api.post('/stripe/checkout?plan=' + plan, {}); window.location.href = url; } catch (err) { setError(err.message || 'Checkout is unavailable.'); setLoading(''); } }
  async function portal() { setLoading('portal'); setError(''); try { const { url } = await api.post('/stripe/portal', {}); window.location.href = url; } catch (err) { setError(err.message || 'Billing portal is unavailable.'); setLoading(''); } }
  return <FeaturePage eyebrow="Plan and usage" title="Billing" description="Keep an eye on plan limits, usage, invoices, and subscription settings.">{error && <div style={{ marginBottom: 18 }}><Alert>{error}</Alert></div>}<FeatureNotice>Usage counters and invoice history will become live when billing usage endpoints are connected. Checkout and the billing portal use the existing Stripe routes.</FeatureNotice><div className="metric-grid"><MetricCard icon="sparkle" label="Current plan" value={profile?.plan || 'Free'} detail="Workspace subscription" tone="violet" /><MetricCard icon="folder" label="Project allowance" value={profile?.plan === 'studio' ? '∞' : profile?.plan === 'solo' ? '5' : '1'} detail="Current plan limit" tone="cyan" /><MetricCard icon="chart" label="Usage tracking" value="—" detail="Not connected" tone="amber" /><MetricCard icon="clock" label="Next invoice" value="—" detail="Not connected" tone="green" /></div><div className="feature-grid">{BILLING_PLANS.map(plan => <section className={'panel price-card ' + (profile?.plan === plan.id ? 'price-card--highlight' : '')} key={plan.id}><span className="price-card__tag">{plan.name}</span><div className="price-card__price"><strong>{plan.price}</strong><span>/ month</span></div><p className="price-card__description">{plan.features}. Includes a 14-day trial.</p><button className="btn btn-primary btn-full" disabled={loading === plan.id || profile?.plan === plan.id} onClick={() => checkout(plan.id)}>{loading === plan.id ? 'Opening checkout…' : profile?.plan === plan.id ? 'Current plan' : 'Choose plan'}</button></section>)}<section className="panel"><div className="panel__header"><div><div className="panel__title">Billing portal</div><div className="panel__subtitle">Payment methods, invoices, and cancellation.</div></div></div><div className="panel__body"><button className="btn btn-secondary" onClick={portal} disabled={loading === 'portal'}>{loading === 'portal' ? <Spinner size={14} /> : <><Icon name="external" size={14} />Open billing portal</>}</button></div></section></div></FeaturePage>;
}
