import { useState } from 'react';
import { Link } from 'react-router-dom';
import { supabase } from '../lib/supabase.js';
import Icon from '../components/Icon.jsx';
import { Alert, LogoMark } from '../components/UI.jsx';

export default function ForgotPassword() {
  const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function handleSubmit(event) { event.preventDefault(); setError(''); setLoading(true); try { const { error: resetError } = await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(), { redirectTo: `${window.location.origin}/reset-password` }); if (resetError) throw resetError; setSent(true); } catch (resetError) { setError(resetError.message || 'Unable to send reset email.'); } finally { setLoading(false); } }
  return <div className="auth-page"><section className="auth-visual"><Link to="/" className="auth-visual__brand"><LogoMark />Loop</Link><div className="auth-visual__content"><p className="eyebrow"><span className="eyebrow__dot" />Account recovery</p><h1>Back to your<br />best work.</h1><p>We’ll help you securely get back into your workspace and keep your review loop moving.</p></div><div className="auth-visual__stats"><div><strong>Secure</strong><span>recovery link</span></div><div><strong>One step</strong><span>to reset</span></div></div></section><main className="auth-card-wrap"><div className="auth-card"><Link to="/" className="auth-card__mobile-brand"><LogoMark small />Loop</Link>{sent ? <><h1>Check your email</h1><p className="auth-card__subtitle">If an account exists for <strong style={{ color: 'var(--text)' }}>{email}</strong>, you’ll receive a secure password reset link shortly.</p><Link className="btn btn-secondary btn-full" to="/login"><Icon name="arrowLeft" size={14} />Back to sign in</Link></> : <><h1>Reset your password</h1><p className="auth-card__subtitle">Enter your account email and we’ll send you a secure reset link.</p>{error && <div style={{ marginBottom: 15 }}><Alert>{error}</Alert></div>}<form className="auth-form" onSubmit={handleSubmit}><div className="form-group"><label className="form-label" htmlFor="reset-email">Email address</label><input id="reset-email" type="email" required autoComplete="email" className="form-input" placeholder="you@company.com" value={email} onChange={event => setEmail(event.target.value)} /></div><button className="btn btn-primary btn-full" disabled={loading}>{loading ? 'Sending reset link…' : 'Send reset link'}<Icon name="arrowRight" size={14} /></button></form><p className="auth-footer"><Link to="/login">Back to sign in</Link></p></>}</div></main></div>;
}
