import { Link } from 'react-router-dom';
import { useAuth } from '../App.jsx';
import Icon from '../components/Icon.jsx';
import { LogoMark } from '../components/UI.jsx';

const features = [
  { icon: 'activity', title: 'Feedback with context', text: 'Pin every note to the exact place on the file so nobody has to decode “top right, near the logo.”' },
  { icon: 'circleCheck', title: 'Approvals that stick', text: 'Turn a vague “looks good” into a clear, timestamped decision your whole team can trust.' },
  { icon: 'layers', title: 'One calm workspace', text: 'Keep files, conversations, and project status together instead of chasing threads across five apps.' },
];

function AppPreview() {
  return <div className="landing-preview"><div className="landing-preview__top"><span /><span /><span /><div className="landing-preview__address">app.loopfeedback.com/project/brand-identity</div></div><div className="landing-preview__body"><div className="landing-preview__rail"><span /><span /><span /><span /></div><div className="landing-preview__canvas"><div className="landing-preview__canvas-bar"><b>Brand identity v3</b><i>Waiting on client</i></div><div className="landing-preview__art"><div className="landing-preview__art-shape" /><div className="landing-preview__pin landing-preview__pin--one">1</div><div className="landing-preview__pin landing-preview__pin--two">2</div></div></div><div className="landing-preview__comments"><p>Feedback thread</p><div><b>Sarah M.</b><span>Can we make the logo a touch larger?</span></div><div><b>You</b><span>On it — uploading v4 shortly.</span></div><em><Icon name="circleCheck" size={13} />Approved</em></div></div></div>;
}

export default function Landing() {
  const { session } = useAuth(); const ctaHref = session ? '/dashboard' : '/signup';
  return <div className="landing-page"><header className="public-header"><Link to="/" className="public-header__brand"><LogoMark small />Loop</Link><nav className="public-nav"><a href="#product">Product</a><a href="#how-it-works">How it works</a><Link to="/pricing">Pricing</Link><Link to={session ? '/dashboard' : '/login'}>Sign in</Link><Link to={ctaHref} className="btn btn-primary btn-sm">Start free trial</Link></nav></header><main><section className="landing-hero" id="product"><div className="landing-hero__copy"><p className="eyebrow"><span className="eyebrow__dot" />The client review workspace</p><h1>Make feedback feel like forward motion.</h1><p>Loop turns scattered client comments into one clear approval thread — pinned to the exact spot on the file.</p><div className="landing-hero__actions"><Link to={ctaHref} className="btn btn-primary">Start your free trial <Icon name="arrowRight" size={15} /></Link><a href="#how-it-works" className="landing-text-link">See how it works <Icon name="arrowRight" size={14} /></a></div><div className="landing-proof"><span className="landing-proof__avatars"><i>SM</i><i>JD</i><i>AC</i></span><span><strong>Built for small creative teams</strong><br /><em>One place to get to “yes.”</em></span></div></div><AppPreview /></section><section className="landing-section" id="how-it-works"><div className="landing-section__intro"><p className="eyebrow"><span className="eyebrow__dot" />A better review loop</p><h2>Less archaeology.<br />More momentum.</h2><p>Loop gives every review a source of truth, so your best work is never held up by a missing message.</p></div><div className="landing-features">{features.map(feature => <article className="landing-feature" key={feature.title}><span className="landing-feature__icon"><Icon name={feature.icon} size={19} /></span><h3>{feature.title}</h3><p>{feature.text}</p></article>)}</div></section><section className="landing-cta"><div><p className="eyebrow"><span className="eyebrow__dot" />Start with one review</p><h2>Give your clients one clear place to say yes.</h2></div><Link to={ctaHref} className="btn btn-primary">Create your workspace <Icon name="arrowRight" size={15} /></Link></section></main><footer className="landing-footer"><span className="public-header__brand"><LogoMark small />Loop</span><span>© 2024 Loop. Built for focused feedback.</span><Link to="/pricing">Pricing</Link></footer></div>;
}
