import { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { signIn } from '../lib/auth.js';
import SocialAuth from '../components/SocialAuth.jsx';
import Icon from '../components/Icon.jsx';
import { Alert, LogoMark } from '../components/UI.jsx';

export default function Login() {
  const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [showPassword, setShowPassword] = useState(false); const navigate = useNavigate(); const [params] = useSearchParams(); const requestedNext = params.get('next'); const next = requestedNext?.startsWith('/') ? requestedNext : '/dashboard';
  async function handleSubmit(e) { e.preventDefault(); setError(''); setLoading(true); try { await signIn(form); navigate(next); } catch (err) { setError(err.message || 'Login failed.'); } finally { setLoading(false); } }
  return <div className="auth-page"><section className="auth-visual"><Link to="/" className="auth-visual__brand"><LogoMark />Loop</Link><div className="auth-visual__content"><p className="eyebrow"><span className="eyebrow__dot" />Workspace for better feedback</p><h1>Ship the work.<br />Keep the signal.</h1><p>One calm, focused space for sharing files, collecting precise feedback, and getting approvals that move projects forward.</p></div><div className="auth-visual__stats"><div><strong>14 days</strong><span>free to try</span></div><div><strong>1 thread</strong><span>per review</span></div><div><strong>0 noise</strong><span>in your inbox</span></div></div></section><main className="auth-card-wrap"><div className="auth-card"><Link to="/" className="auth-card__mobile-brand"><LogoMark small />Loop</Link><h1>Welcome back</h1><p className="auth-card__subtitle">Sign in to your workspace and pick up where you left off.</p>{error && <Alert>{error}</Alert>}<form className="auth-form" onSubmit={handleSubmit}><div className="form-group"><label className="form-label" htmlFor="email">Email address</label><input id="email" type="email" required autoComplete="email" spellCheck="false" className="form-input" placeholder="you@company.com" value={form.email} onChange={e => setForm(f => ({ ...f, email: e.target.value }))} /></div><div className="form-group"><div className="auth-form__row"><label className="form-label" htmlFor="password">Password</label><Link className="auth-form__link" to="/forgot-password">Forgot password?</Link></div><div style={{ position: 'relative' }}><input id="password" type={showPassword ? 'text' : 'password'} required autoComplete="current-password" className="form-input" placeholder="Enter your password" value={form.password} onChange={e => setForm(f => ({ ...f, password: e.target.value }))} style={{ paddingRight: '42px' }} /><button type="button" className="icon-button" onClick={() => setShowPassword(value => !value)} aria-label={showPassword ? 'Hide password' : 'Show password'} style={{ position: 'absolute', right: 4, top: 4 }}><Icon name="lock" size={16} /></button></div></div><label className="auth-form__row" style={{ justifyContent: 'flex-start', gap: 8, color: 'var(--text-muted)', fontSize: 11 }}><input type="checkbox" /> Remember me</label><button type="submit" className="btn btn-primary btn-full" disabled={loading}>{loading ? 'Signing in…' : 'Sign in to Loop'}<Icon name="arrowRight" size={15} /></button></form><SocialAuth redirectTo={next} onError={setError} /><p className="auth-footer">Don&apos;t have an account? <Link to="/signup">Create a free workspace</Link></p></div></main></div>;
}
