import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { api } from '../lib/api.js';
import Spinner from '../components/Spinner.jsx';
import Icon from '../components/Icon.jsx';
import { Alert, LogoMark } from '../components/UI.jsx';

const STEPS = [
  { icon: 'upload', title: 'Share the file', desc: 'Drop in a design, PDF, or image. Your client opens it right in the browser — no account, no download.' },
  { icon: 'activity', title: 'Collect feedback in place', desc: 'Clients click anywhere on the file to drop a comment pin. Feedback stays tied to the exact spot.' },
  { icon: 'circleCheck', title: 'Get a clear approval', desc: 'One click marks a version approved, with a timestamp and the approver’s name.' },
];

export default function Onboarding() {
  const [step, setStep] = useState(0); const [form, setForm] = useState({ name: '', client_name: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  async function handleCreate(e) { e.preventDefault(); if (!form.name.trim()) { setError('Give your project a name.'); return; } setError(''); setLoading(true); try { const project = await api.post('/projects', { name: form.name.trim(), client_name: form.client_name.trim() || null }); navigate(`/project/${project.id}`); } catch (err) { setError(err.message || 'Failed to create project.'); setLoading(false); } }

  return <div className="auth-page" style={{ gridTemplateColumns: 'minmax(0,1fr) minmax(380px,540px)' }}><section className="auth-visual"><Link to="/dashboard" className="auth-visual__brand"><LogoMark />Loop</Link><div className="auth-visual__content"><p className="eyebrow"><span className="eyebrow__dot" />Your first five minutes</p><h1>Set up a review that runs itself.</h1><p>Start with one project. Loop keeps every file, comment, and approval in one calm, searchable thread.</p></div><div className="auth-visual__stats"><div><strong>01</strong><span>name a project</span></div><div><strong>02</strong><span>share your file</span></div><div><strong>03</strong><span>get approval</span></div></div></section><main className="auth-card-wrap"><div className="auth-card"><Link to="/dashboard" className="auth-card__mobile-brand"><LogoMark small />Loop</Link><div className="eyebrow"><span className="eyebrow__dot" />Step {step + 1} of 2</div>{step === 0 ? <><h1 style={{ marginTop: 14 }}>Welcome to Loop</h1><p className="auth-card__subtitle">Client feedback, finally out of your inbox.</p><div className="settings-stack" style={{ gap: 9, margin: '25px 0' }}>{STEPS.map(item => <div className="panel" key={item.title} style={{ padding: 14, display: 'flex', gap: 12, alignItems: 'flex-start' }}><div className="quick-action__icon"><Icon name={item.icon} size={16} /></div><div><strong style={{ display: 'block', color: 'var(--text)', fontSize: 12 }}>{item.title}</strong><span className="muted" style={{ display: 'block', fontSize: 11, marginTop: 3 }}>{item.desc}</span></div></div>)}</div><button className="btn btn-primary" onClick={() => setStep(1)}>Create my first project <Icon name="arrowRight" size={15} /></button></> : <><button className="btn btn-ghost btn-sm" onClick={() => setStep(0)} style={{ paddingLeft: 0 }}><Icon name="arrowLeft" size={14} />Back</button><h1 style={{ marginTop: 17 }}>Name your first project</h1><p className="auth-card__subtitle">You can always change this later.</p>{error && <Alert>{error}</Alert>}<form className="auth-form" onSubmit={handleCreate}><div className="form-group"><label className="form-label" htmlFor="pn">Project name</label><input id="pn" type="text" required className="form-input" placeholder="Brand Identity v3" value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} /></div><div className="form-group"><label className="form-label" htmlFor="cn">Client name <span className="muted">(optional)</span></label><input id="cn" type="text" className="form-input" placeholder="Sarah M." value={form.client_name} onChange={e => setForm(f => ({ ...f, client_name: e.target.value }))} /></div><button type="submit" className="btn btn-primary btn-full" disabled={loading}>{loading ? <><Spinner size={15} color="#fff" />Creating project…</> : <>Create project <Icon name="arrowRight" size={15} /></>}</button></form></>}</div></main></div>;
}
