import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase.js';
import Icon from '../components/Icon.jsx';
import { Alert, LogoMark } from '../components/UI.jsx';

export default function ResetPassword() {
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(false); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  async function handleSubmit(event) { event.preventDefault(); setError(''); if (password.length < 8) { setError('Use at least 8 characters.'); return; } if (password !== confirm) { setError('Passwords do not match.'); return; } setLoading(true); try { const { error: updateError } = await supabase.auth.updateUser({ password }); if (updateError) throw updateError; setSuccess(true); setTimeout(() => navigate('/dashboard'), 900); } catch (updateError) { setError(updateError.message || 'Unable to update password.'); } finally { setLoading(false); } }
  return <div className="auth-page"><section className="auth-visual"><Link to="/" className="auth-visual__brand"><LogoMark />Loop</Link><div className="auth-visual__content"><p className="eyebrow"><span className="eyebrow__dot" />Account recovery</p><h1>Set a new<br />baseline.</h1><p>Choose a strong password and you’ll be right back in the workspace.</p></div></section><main className="auth-card-wrap"><div className="auth-card"><Link to="/" className="auth-card__mobile-brand"><LogoMark small />Loop</Link><h1>Choose a new password</h1><p className="auth-card__subtitle">Use a password you don’t use anywhere else.</p>{error && <div style={{ marginBottom: 15 }}><Alert>{error}</Alert></div>}{success && <div style={{ marginBottom: 15 }}><Alert tone="success">Password updated. Opening your workspace…</Alert></div>}<form className="auth-form" onSubmit={handleSubmit}><div className="form-group"><label className="form-label" htmlFor="new-password">New password</label><input id="new-password" type="password" required autoComplete="new-password" className="form-input" placeholder="At least 8 characters" value={password} onChange={event => setPassword(event.target.value)} /></div><div className="form-group"><label className="form-label" htmlFor="confirm-password">Confirm password</label><input id="confirm-password" type="password" required autoComplete="new-password" className="form-input" placeholder="Repeat your password" value={confirm} onChange={event => setConfirm(event.target.value)} /></div><button className="btn btn-primary btn-full" disabled={loading || success}>{loading ? 'Updating password…' : 'Update password'}<Icon name="check" size={14} /></button></form></div></main></div>;
}
